spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  flyway:
    enabled: true
    baseline-on-migrate: true
  liquibase:
    change-log: /db/changelog/db.changelog.xml
